version: "3"
services:
  tor:
    image: dperson/torproxy:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  v2ray:
    image: v2ray/official:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "40109:40109/udp"
    command: "v2ray -config=/etc/v2ray/config.json"
    networks:
      - webnet
    volumes:
      - ./v2ray:/etc/v2ray
networks:
  webnet:
